version: 2
updates:
    - package-ecosystem: cargo
      directory: "/"
      schedule:
          interval: daily
          time: "03:00"
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: async-trait
            versions:
                - 0.1.48
                - 0.1.49
          - dependency-name: futures-core
            versions:
                - 0.3.13
                - 0.3.14
          - dependency-name: futures-channel
            versions:
                - 0.3.14
          - dependency-name: anyhow
            versions:
                - 1.0.40
          - dependency-name: elliptic-curve
            versions:
                - 0.9.0
                - 0.9.2
                - 0.9.6
          - dependency-name: pin-project
            versions:
                - 1.0.6
          - dependency-name: arrayvec
            versions:
                - 0.6.0
          - dependency-name: serde
            versions:
                - 1.0.125
          - dependency-name: tokio
            versions:
                - 1.3.0
          - dependency-name: serde_json
            versions:
                - 1.0.63
          - dependency-name: ethereum-types
            versions:
                - 0.11.0
          - dependency-name: yubihsm
            versions:
                - 0.38.0
