[package]
name = "ethers-etherscan"
version = "0.1.1"
authors = ["Matthias Seitz <matthias.seitz@outlook.de>", "Georgios Konstantopoulos <me@gakonst.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "../README.md"
documentation = "https://docs.rs/ethers"
repository = "https://github.com/gakonst/ethers-rs"
homepage = "https://docs.rs/ethers"
description = """
Rust API bindings for the etherscan.io web API
"""
keywords = ["ethereum", "web3", "etherscan", "ethers"]

[dependencies]
ethers-core = { version = "^0.5.0", path = "../ethers-core", default-features = false }
reqwest = { version = "0.11.6", features = ["json"] }
serde = { version = "1.0.124", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.64", default-features = false }
thiserror = "1.0.29"

[dev-dependencies]
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
