[package]
name = "ethers-derive-eip712"
version = "0.1.0"
edition = "2018"
description = "Custom derive macro for EIP-712 typed data"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = "1.0.77"
ethers-core = { version = "^0.5.0", path = "../", default-features = false, features = ["eip712"] }
hex = "0.4.3"
serde = "1.0.130"
serde_json = "1.0.68"
proc-macro2 = "1.0.29"

[dev-dependencies]
ethers-contract = { version = "^0.5.0", path = "../../ethers-contract"}
ethers-contract-derive = { version = "^0.5.0", path = "../../ethers-contract/ethers-contract-derive" }
ethers-signers = { version = "^0.5.0", path = "../../ethers-signers" }