[package]
name = "ethers-middleware"
license = "MIT OR Apache-2.0"
version = "0.4.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"
description = "Middleware implementations for the ethers-rs crate"
homepage = "https://docs.rs/ethers"
repository = "https://github.com/gakonst/ethers-rs"
keywords = ["ethereum", "web3", "celo", "ethers"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ethers-contract = { version = "0.4.0", path = "../ethers-contract", default-features = false, features = ["abigen"] }
ethers-core = { version = "0.4.0", path = "../ethers-core", default-features = false }
ethers-providers = { version = "0.4.0", path = "../ethers-providers", default-features = false }
ethers-signers = { version = "0.4.0", path = "../ethers-signers", default-features = false }

async-trait = { version = "0.1.50", default-features = false }
serde = { version = "1.0.124", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26", default-features = false }
futures-util = { version = "0.3.16", default-features = false }
tracing = { version = "0.1.26", default-features = false }
tracing-futures = { version = "0.2.5", default-features = false }

# for gas oracles
serde-aux = { version = "2.2.0", default-features = false }
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
url = { version = "2.2.2", default-features = false }

serde_json = { version = "1.0.64", default-features = false }
tokio = { version = "1.5" }

[dev-dependencies]
ethers = { version = "0.4.0", path = "../ethers" }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
rand = { version = "0.8.4", default-features = false }
tokio = { version = "1.5", default-features = false, features = ["rt", "macros", "time"] }

[features]
celo = ["ethers-core/celo", "ethers-providers/celo", "ethers-signers/celo"]
