[package]
name = "ethers-addressbook"
version = "0.17.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
description = "Common Ethereum name to address mappings"
homepage = "https://docs.rs/ethers"
repository = "https://github.com/gakonst/ethers-rs"
keywords = ["ethereum", "web3", "celo", "ethers"]

[dependencies]
once_cell = "1.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

ethers-core = { path = "../ethers-core", version = "^0.17.0" }
