[package]
name = "ethers-contract"
license = "MIT OR Apache-2.0"
version = "0.4.7"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"
description = "Smart contract bindings for the ethers-rs crate"
homepage = "https://docs.rs/ethers"
repository = "https://github.com/gakonst/ethers-rs"
keywords = ["ethereum", "web3", "celo", "ethers"]

[dependencies]
ethers-providers = { version = "0.4.6", path = "../ethers-providers", default-features = false }
ethers-core = { version = "0.4.6", path = "../ethers-core", default-features = false }
ethers-contract-abigen = { version = "0.4.7", path = "ethers-contract-abigen", optional = true }
ethers-contract-derive = { version = "0.4.7", path = "ethers-contract-derive", optional = true }

serde = { version = "1.0.124", default-features = false }
serde_json = { version = "1.0.64", default-features = false }
thiserror = { version = "1.0.26", default-features = false }
once_cell = { version = "1.8.0" }
pin-project = {version = "1.0.7", default-features = false }
futures-util = { version = "0.3.16" }
hex = { version = "0.4.3", default-features = false, features = ["std"] }

[dev-dependencies]
ethers = { version = "0.4.0", path = "../ethers" }
ethers-providers = { version = "0.4.6", path = "../ethers-providers", default-features = false, features = ["ws"] }
ethers-signers = { version = "0.4.6", path = "../ethers-signers" }
ethers-middleware = { version = "0.4.8", path = "../ethers-middleware" }
tokio = { version = "1.5", default-features = false, features = ["macros"] }


[features]
abigen = ["ethers-contract-abigen", "ethers-contract-derive"]
celo = ["legacy", "ethers-core/celo", "ethers-core/celo", "ethers-providers/celo"]
legacy = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
