[package]
name = "ethers-contract"
license = "MIT OR Apache-2.0"
version = "0.1.3"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"
description = "Smart contract bindings for the ethers-rs crate"
homepage = "https://docs.rs/ethers"
repository = "https://github.com/gakonst/ethers-rs"
keywords = ["ethereum", "web3", "celo", "ethers"]

[dependencies]
ethers-contract-abigen = { version = "0.1.3", path = "ethers-contract-abigen", optional = true }
ethers-contract-derive = { version = "0.1.3", path = "ethers-contract-derive", optional = true }

ethers-providers = { version = "0.1.3", path = "../ethers-providers" }
ethers-core = { version = "0.1.3", path = "../ethers-core" }

serde = { version = "1.0.110", default-features = false }
serde_json = "1.0.55"
rustc-hex = { version = "2.1.0", default-features = false }
thiserror = { version = "1.0.15", default-features = false }
once_cell = { version = "1.3.1", default-features = false }
futures = "0.3.5"

[dev-dependencies]
ethers = { version = "0.1.3", path = "../ethers" }
tokio = { version = "0.2.21", default-features = false, features = ["macros"] }
serde_json = "1.0.55"

ethers-signers = { version = "0.1.3", path = "../ethers-signers" }
ethers-middleware = { version = "0.1.3", path = "../ethers-middleware" }

[features]
abigen = ["ethers-contract-abigen", "ethers-contract-derive"]
celo = ["ethers-core/celo", "ethers-core/celo", "ethers-providers/celo"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
