name: deps

on:
    push:
        branches: [master]
        paths: [Cargo.lock]
    pull_request:
        branches: [master]
        paths: [Cargo.lock]

env:
    RUSTFLAGS: -D warnings
    CARGO_TERM_COLOR: always

concurrency: deps-${{ github.head_ref || github.run_id }}

jobs:
    deny:
        name: deny (${{ matrix.checks }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                checks:
                    - advisories
                    - bans licenses sources

        continue-on-error: ${{ matrix.checks == 'advisories' }}

        steps:
            - uses: actions/checkout@v3
            - uses: EmbarkStudios/cargo-deny-action@v1
              with:
                  command: check ${{ matrix.checks }}
